// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Data_VizualizerML.Model
{
    public class ModelInput
    {
        [ColumnName("marketplace"), LoadColumn(0)]
        public string Marketplace { get; set; }


        [ColumnName("customer_id"), LoadColumn(1)]
        public float Customer_id { get; set; }


        [ColumnName("review_id"), LoadColumn(2)]
        public string Review_id { get; set; }


        [ColumnName("product_id"), LoadColumn(3)]
        public string Product_id { get; set; }


        [ColumnName("product_parent"), LoadColumn(4)]
        public float Product_parent { get; set; }


        [ColumnName("product_title"), LoadColumn(5)]
        public string Product_title { get; set; }


        [ColumnName("product_category"), LoadColumn(6)]
        public string Product_category { get; set; }


        [ColumnName("star_rating"), LoadColumn(7)]
        public float Star_rating { get; set; }


        [ColumnName("helpful_votes"), LoadColumn(8)]
        public float Helpful_votes { get; set; }


        [ColumnName("total_votes"), LoadColumn(9)]
        public float Total_votes { get; set; }


        [ColumnName("vine"), LoadColumn(10)]
        public bool Vine { get; set; }


        [ColumnName("verified_purchase"), LoadColumn(11)]
        public bool Verified_purchase { get; set; }


        [ColumnName("review_headline"), LoadColumn(12)]
        public string Review_headline { get; set; }


        [ColumnName("review_body"), LoadColumn(13)]
        public string Review_body { get; set; }


        [ColumnName("review_date"), LoadColumn(14)]
        public string Review_date { get; set; }


    }
}
