// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Data_VizualizerML.Model;

namespace Data_VizualizerML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\Deepang\OneDrive\Desktop\amazon_reviews_us_Digital_Software_v1_00.tsv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Star_rating with predicted Star_rating from sample data...\n\n");
            Console.WriteLine($"marketplace: {sampleData.Marketplace}");
            Console.WriteLine($"customer_id: {sampleData.Customer_id}");
            Console.WriteLine($"review_id: {sampleData.Review_id}");
            Console.WriteLine($"product_id: {sampleData.Product_id}");
            Console.WriteLine($"product_parent: {sampleData.Product_parent}");
            Console.WriteLine($"product_title: {sampleData.Product_title}");
            Console.WriteLine($"product_category: {sampleData.Product_category}");
            Console.WriteLine($"helpful_votes: {sampleData.Helpful_votes}");
            Console.WriteLine($"total_votes: {sampleData.Total_votes}");
            Console.WriteLine($"vine: {sampleData.Vine}");
            Console.WriteLine($"verified_purchase: {sampleData.Verified_purchase}");
            Console.WriteLine($"review_headline: {sampleData.Review_headline}");
            Console.WriteLine($"review_body: {sampleData.Review_body}");
            Console.WriteLine($"review_date: {sampleData.Review_date}");
            Console.WriteLine($"\n\nActual Star_rating: {sampleData.Star_rating} \nPredicted Star_rating: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: '\t',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
