// <auto-generated />
namespace Data_Vizualizer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bhagwan2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bhagwan2));
        
        string IMigrationMetadata.Id
        {
            get { return "201911271206172_bhagwan2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
